// SQL for RME3 Connections (spec 2026-10-03-rme3-module-platform-v2 §10.3-10.4),
// generated by Runly ORM for each connection when a module is installed or
// updated: a real FK from the source table's targetField to the core table
// (so hard deletes of core records cascade / null / restrict in the database
// itself), a 1:1 unique index for `fields` connections, and a trigger that
// keeps public.connection_record in sync on every INSERT/UPDATE/DELETE —
// whatever code path writes the source table (generated API, core form save,
// MirAI, imports, hand-written SQL, FK cascades).
import { createHash } from 'node:crypto'
import { ModuleEngineError } from './errors.js'

const IDENTIFIER_RE = /^[a-z_][a-z0-9_]{0,62}$/
const LITERAL_RE = /^[a-z0-9_.-]{1,80}$/
const DELETE_ACTIONS = { cascade: 'CASCADE', setNull: 'SET NULL', restrict: 'RESTRICT' }
export const CONNECTION_OBJECT_PREFIX = 'runly_conn_'

function ident(value, label) {
  if (!IDENTIFIER_RE.test(String(value ?? ''))) {
    throw new ModuleEngineError(`connection SQL: ${label} "${value}" is not a safe identifier`, 'AME_UNSAFE_IDENTIFIER')
  }
  return `"${value}"`
}

function literal(value, label) {
  if (!LITERAL_RE.test(String(value ?? ''))) {
    throw new ModuleEngineError(`connection SQL: ${label} "${value}" contains unsafe characters`, 'AME_UNSAFE_IDENTIFIER')
  }
  return `'${value}'`
}

// Deterministic object names; long ones fall back to a hash (Postgres 63-char limit).
export function connectionObjectNames(moduleKey, connectionKey) {
  const slug = String(moduleKey).split('.').pop()
  let base = `${CONNECTION_OBJECT_PREFIX}${slug}_${connectionKey}`
  if (base.length > 55) base = `${CONNECTION_OBJECT_PREFIX}${createHash('sha256').update(`${moduleKey}:${connectionKey}`).digest('hex').slice(0, 16)}`
  return { base, fk: `${base}_fk`, unique: `${base}_uq`, fn: `${base}_fn`, trigger: `${base}_trg` }
}

function validated(spec) {
  const { moduleKey, connection, sourceTable, targetTable, targetType } = spec
  const mk = literal(moduleKey, 'moduleKey')
  const ck = literal(connection.key, 'connection.key')
  return {
    names: connectionObjectNames(moduleKey, connection.key),
    mk,
    ck,
    tt: literal(targetType, 'targetType'),
    src: ident(sourceTable, 'sourceTable'),
    target: ident(targetTable, 'targetTable'),
    tf: ident(connection.targetField, 'targetField'),
    offered: (spec.offeredColumns ?? []).map((column) => ({ name: column, sql: ident(column, 'offered column') })),
    search: (spec.searchColumns ?? []).map((column) => ident(column, 'search column')),
    hasEnabled: spec.hasEnabled !== false,
    hasUpdatedAt: spec.hasUpdatedAt !== false,
  }
}

// Rows of the source table whose targetField points at a missing core record
// (checked before validating the FK; the caller reports them as a blocker).
export function buildOrphanCountSql(spec) {
  const v = validated(spec)
  return `SELECT count(*)::int AS orphans FROM public.${v.src} s WHERE s.${v.tf} IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.${v.target} t WHERE t."id" = s.${v.tf})`
}

function recordValues(v, row) {
  const data = v.offered.length
    ? `jsonb_build_object(${v.offered.map((column) => `'${column.name}', ${row}.${column.sql}`).join(', ')})`
    : `'{}'::jsonb`
  const search = v.search.length
    ? `to_tsvector('simple', concat_ws(' ', ${v.search.map((column) => `${row}.${column}::text`).join(', ')}))`
    : 'NULL'
  return {
    data,
    search,
    enabled: v.hasEnabled ? `${row}."enabled"` : 'true',
    updatedAt: v.hasUpdatedAt ? `${row}."updated_at"` : 'now()',
  }
}

const UPSERT_TAIL = `ON CONFLICT (module_key, connection_key, source_record_id) DO UPDATE SET
      company_id = EXCLUDED.company_id, target_type = EXCLUDED.target_type, target_id = EXCLUDED.target_id,
      enabled = EXCLUDED.enabled, data = EXCLUDED.data, search_text = EXCLUDED.search_text, updated_at = EXCLUDED.updated_at`

// Statements to (re)create the connection objects, in order. Idempotent: safe
// to run on every install/update of the module.
export function buildConnectionSql(spec) {
  const v = validated(spec)
  const action = DELETE_ACTIONS[spec.connection.kind === 'fields' ? 'cascade' : spec.connection.onTargetDelete]
  if (!action) throw new ModuleEngineError(`connection SQL: unknown onTargetDelete "${spec.connection.onTargetDelete}"`, 'AME_CONNECTION_POLICY')
  const n = v.names
  const values = recordValues(v, 'NEW')
  const statements = []
  if (spec.connection.kind === 'fields') {
    statements.push(`CREATE UNIQUE INDEX IF NOT EXISTS "${n.unique}" ON public.${v.src} ("company_id", ${v.tf})`)
  }
  statements.push(
    `ALTER TABLE public.${v.src} DROP CONSTRAINT IF EXISTS "${n.fk}"`,
    `ALTER TABLE public.${v.src} ADD CONSTRAINT "${n.fk}" FOREIGN KEY (${v.tf}) REFERENCES public.${v.target} ("id") ON DELETE ${action} NOT VALID`,
    `ALTER TABLE public.${v.src} VALIDATE CONSTRAINT "${n.fk}"`,
    `CREATE OR REPLACE FUNCTION public."${n.fn}"() RETURNS trigger LANGUAGE plpgsql AS $runly_conn$
BEGIN
  IF TG_OP = 'DELETE' THEN
    DELETE FROM public.connection_record WHERE module_key = ${v.mk} AND connection_key = ${v.ck} AND source_record_id = OLD."id";
    RETURN OLD;
  END IF;
  IF NEW.${v.tf} IS NULL THEN
    DELETE FROM public.connection_record WHERE module_key = ${v.mk} AND connection_key = ${v.ck} AND source_record_id = NEW."id";
    RETURN NEW;
  END IF;
  INSERT INTO public.connection_record (company_id, module_key, connection_key, target_type, target_id, source_record_id, enabled, data, search_text, updated_at)
    VALUES (NEW."company_id", ${v.mk}, ${v.ck}, ${v.tt}, NEW.${v.tf}, NEW."id", ${values.enabled}, ${values.data}, ${values.search}, ${values.updatedAt})
    ${UPSERT_TAIL};
  RETURN NEW;
END
$runly_conn$`,
    `DROP TRIGGER IF EXISTS "${n.trigger}" ON public.${v.src}`,
    `CREATE TRIGGER "${n.trigger}" AFTER INSERT OR UPDATE OR DELETE ON public.${v.src} FOR EACH ROW EXECUTE FUNCTION public."${n.fn}"()`,
  )
  return statements
}

// Fills the index from existing rows (activation, reinstall, rebuild).
export function buildBackfillSql(spec) {
  const v = validated(spec)
  const values = recordValues(v, 's')
  return `INSERT INTO public.connection_record (company_id, module_key, connection_key, target_type, target_id, source_record_id, enabled, data, search_text, updated_at)
    SELECT s."company_id", ${v.mk}, ${v.ck}, ${v.tt}, s.${v.tf}, s."id", ${values.enabled}, ${values.data}, ${values.search}, ${values.updatedAt}
    FROM public.${v.src} s WHERE s.${v.tf} IS NOT NULL
    ${UPSERT_TAIL}`
}

// Removes the connection objects and its index rows; never drops data columns.
export function buildDropConnectionSql(spec) {
  const v = validated(spec)
  const n = v.names
  return [
    `DROP TRIGGER IF EXISTS "${n.trigger}" ON public.${v.src}`,
    `DROP FUNCTION IF EXISTS public."${n.fn}"()`,
    `ALTER TABLE public.${v.src} DROP CONSTRAINT IF EXISTS "${n.fk}"`,
    `DROP INDEX IF EXISTS public."${n.unique}"`,
    `DELETE FROM public.connection_record WHERE module_key = ${v.mk} AND connection_key = ${v.ck}`,
  ]
}

export function isConnectionConstraint(name) {
  return String(name ?? '').startsWith(CONNECTION_OBJECT_PREFIX)
}
