import { createModuleManifest, MODULE_KINDS } from "@runly/core";

export const contactsMap = createModuleManifest({
  key: "runly.contacts",
  name: "Contactos",
  description: "Clientes, proveedores, personas y empresas.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "ContactRound",
  color: "#0ea5e9",
  pwa: { shortName: "Contactos", startPath: "/contacts" },
  category: "operaciones",
  summary: "Clientes, proveedores, personas y empresas",
  dependencies: [{ key: "runly.core" }, { key: "runly.identity" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["Contact"],
    sharedEntities: ["Company", "AuditLog"],
  },
  navigation: [
    {
      label: "Contactos",
      path: "/contacts",
      icon: "Contact",
      layout: "main",
      permissionKey: "contacts.contacts.read",
    },
  ],
  permissions: [
    { key: "contacts.access", name: "Access Contacts" },
    { key: "contacts.contacts.read", name: "Read Contacts Feature" },
    { key: "contacts.contacts.create", name: "Create Contacts Feature" },
    { key: "contacts.contacts.update", name: "Update Contacts Feature" },
    { key: "contacts.contacts.delete", name: "Delete Contacts Feature" },
  ],
  exposes: {
    contactPicker: true,
    getContactById: true,
  },
  acl: {
    module: "contacts.access",
    actions: {
      "contacts.contacts.read": "contacts.contacts.read",
      "contacts.contacts.create": "contacts.contacts.create",
      "contacts.contacts.update": "contacts.contacts.update",
      "contacts.contacts.delete": "contacts.contacts.delete",
      "contacts.list": "contacts.contacts.read",
      "contacts.picker": "contacts.contacts.read",
      "contacts.enabled": "contacts.contacts.update",
    },
    models: {
      Contact: {
        read: "contacts.contacts.read",
        create: "contacts.contacts.create",
        update: "contacts.contacts.update",
        delete: "contacts.contacts.delete",
      },
    },
  },
  blueprints: [
    {
      key: "contacts.contact.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "Contact",
        label: "Contacto",
        fields: [
          {
            name: "type",
            label: "Tipo",
            type: "select",
            options: ["customer", "supplier", "person", "company"],
            required: true,
          },
          { name: "name", label: "Nombre", type: "text", required: true },
          { name: "legalName", label: "Nombre legal", type: "text" },
          { name: "email", label: "Correo", type: "email" },
          { name: "phone", label: "Telefono", type: "phone" },
          { name: "taxId", label: "RFC / Tax ID", type: "text" },
          {
            name: "notesMarkdown",
            label: "Observaciones",
            type: "markdown",
            maxLength: 5000,
          },
        ],
        table: { columns: ["type", "name", "email", "phone", "taxId"] },
      },
    },
  ],
});

export const hrMap = createModuleManifest({
  key: "runly.hr",
  name: "Recursos Humanos",
  description: "Colaboradores, notas internas y expedientes.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "UsersRound",
  color: "#2563eb",
  pwa: { shortName: "RRHH", startPath: "/hr/employees" },
  category: "operaciones",
  summary: "Gestión de personal y expediente",
  dependencies: [{ key: "runly.core" }, { key: "runly.files", optional: true }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["HrEmployee", "HrDepartment", "HrJobTitle"],
    sharedEntities: ["Company", "UserProfile", "FileAsset", "AuditLog"],
  },
  navigation: [
    {
      label: "Colaboradores",
      path: "/hr/employees",
      icon: "Users",
      layout: "main",
      permissionKey: "hr.employee.read",
    },
    {
      label: "Organigrama",
      path: "/hr/org-chart",
      icon: "Network",
      layout: "main",
      permissionKey: "hr.org_chart.read",
    },
    {
      label: "Catálogos",
      path: "/hr/catalogs",
      icon: "BookOpen",
      layout: "main",
      permissionKey: "hr.department.read",
    },
  ],
  permissions: [
    { key: "hr.access", name: "Access HR" },
    { key: "hr.employee.read", name: "Read HR Employees" },
    { key: "hr.employee.create", name: "Create HR Employees" },
    { key: "hr.employee.update", name: "Update HR Employees" },
    { key: "hr.employee.delete", name: "Delete HR Employees" },
    { key: "hr.department.read", name: "Read HR Departments" },
    { key: "hr.department.create", name: "Create HR Departments" },
    { key: "hr.department.update", name: "Update HR Departments" },
    { key: "hr.department.delete", name: "Delete HR Departments" },
    { key: "hr.job_title.read", name: "Read HR Job Titles" },
    { key: "hr.job_title.create", name: "Create HR Job Titles" },
    { key: "hr.job_title.update", name: "Update HR Job Titles" },
    { key: "hr.job_title.delete", name: "Delete HR Job Titles" },
    { key: "hr.org_chart.read", name: "Read HR Org Chart" },
    { key: "hr.org_chart.create", name: "Create HR Org Chart" },
    { key: "hr.org_chart.update", name: "Update HR Org Chart" },
    { key: "hr.org_chart.delete", name: "Delete HR Org Chart" },
  ],
  acl: {
    module: "hr.access",
    actions: {
      "hr.employee.read": "hr.employee.read",
      "hr.employee.create": "hr.employee.create",
      "hr.employee.update": "hr.employee.update",
      "hr.employee.delete": "hr.employee.delete",
      "hr.employee.enable": "hr.employee.update",
      "hr.employee.disable": "hr.employee.update",
      "hr.employee.file.attach": "hr.employee.update",
      "hr.employee.file.delete": "hr.employee.update",
      "hr.department.read": "hr.department.read",
      "hr.department.create": "hr.department.create",
      "hr.department.update": "hr.department.update",
      "hr.department.delete": "hr.department.delete",
      "hr.job_title.read": "hr.job_title.read",
      "hr.job_title.create": "hr.job_title.create",
      "hr.job_title.update": "hr.job_title.update",
      "hr.job_title.delete": "hr.job_title.delete",
      "hr.org_chart.read": "hr.org_chart.read",
      "hr.org_chart.create": "hr.org_chart.create",
      "hr.org_chart.update": "hr.org_chart.update",
      "hr.org_chart.delete": "hr.org_chart.delete",
    },
    models: {
      HrEmployee: {
        read: "hr.employee.read",
        create: "hr.employee.create",
        update: "hr.employee.update",
        delete: "hr.employee.delete",
      },
      HrDepartment: {
        read: "hr.department.read",
        create: "hr.department.create",
        update: "hr.department.update",
        delete: "hr.department.delete",
      },
      HrJobTitle: {
        read: "hr.job_title.read",
        create: "hr.job_title.create",
        update: "hr.job_title.update",
        delete: "hr.job_title.delete",
      },
    },
  },
  blueprints: [
    {
      key: "hr.employee.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "HrEmployee",
        label: "Colaborador",
        fields: [
          { name: "employeeCode", label: "Codigo", type: "text" },
          { name: "userProfileId", label: "Cuenta de usuario", type: "text" },
          { name: "firstName", label: "Nombre", type: "text", required: true },
          {
            name: "lastName",
            label: "Apellidos",
            type: "text",
            required: true,
          },
          { name: "workEmail", label: "Correo laboral", type: "email" },
          { name: "personalEmail", label: "Correo personal", type: "email" },
          { name: "phone", label: "Teléfono", type: "phone" },
          {
            name: "emergencyContactName",
            label: "Contacto de emergencia",
            type: "text",
          },
          {
            name: "emergencyContactPhone",
            label: "Telefono de emergencia",
            type: "phone",
          },
          { name: "jobTitle", label: "Puesto", type: "text" },
          { name: "department", label: "Departamento", type: "text" },
          { name: "managerName", label: "Supervisor", type: "text" },
          {
            name: "employmentType",
            label: "Tipo de empleo",
            type: "select",
            options: ["full_time", "part_time", "contractor", "intern"],
          },
          { name: "workLocation", label: "Ubicacion de trabajo", type: "text" },
          { name: "terminationDate", label: "Fecha de baja", type: "text" },
          {
            name: "status",
            label: "Estado",
            type: "select",
            options: ["active", "inactive", "vacation", "terminated"],
            required: true,
          },
          { name: "notesMarkdown", label: "Notas", type: "markdown" },
        ],
      },
    },
  ],
});

export const runlyWebsiteManifest = createModuleManifest({
  key: "runly.website",
  name: "Sitio web",
  description:
    "Sitio web publico, editor visual de paginas y publicacion de contenido.",
  version: "0.2.0",
  kind: MODULE_KINDS.WEBSITE,
  core: true,
  uninstallable: false,
  icon: "Globe",
  color: "#6366f1",
  pwa: { shortName: "Sitio web", startPath: "/" },
  summary: "CMS, editor Puck y publicacion de paginas.",
  dependencies: [{ key: "runly.core" }],
  lifecycle: {
    installable: true,
    uninstallable: true,
    resettable: true,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: [],
    sharedEntities: ["Company", "AuditLog"],
  },
  permissions: [
    { key: "website.access", name: "Acceso al Sitio web" },
    { key: "website.site.read", name: "Ver configuracion del sitio" },
    { key: "website.site.update", name: "Editar configuracion del sitio" },
    { key: "website.pages.read", name: "Ver paginas" },
    { key: "website.pages.create", name: "Crear paginas" },
    { key: "website.pages.update", name: "Editar paginas" },
    { key: "website.pages.publish", name: "Publicar paginas" },
    { key: "website.pages.delete", name: "Eliminar paginas" },
    { key: "website.theme.read", name: "Ver temas" },
    { key: "website.theme.update", name: "Editar temas" },
    { key: "website.menus.read", name: "Ver menus" },
    { key: "website.menus.update", name: "Editar menus" },
    { key: "website.dist.upload", name: "Subir build del sitio" },
  ],
  acl: {
    module: "website.access",
    actions: {
      "website.site.read": "website.site.read",
      "website.site.update": "website.site.update",
      "website.pages.read": "website.pages.read",
      "website.pages.create": "website.pages.create",
      "website.pages.update": "website.pages.update",
      "website.pages.publish": "website.pages.publish",
      "website.pages.delete": "website.pages.delete",
      "website.theme.read": "website.theme.read",
      "website.theme.update": "website.theme.update",
      "website.menus.read": "website.menus.read",
      "website.menus.update": "website.menus.update",
    },
  },
  navigation: [
    {
      label: 'Sitio web',
      path: '/',
      icon: 'Globe',
      layout: 'main',
      permissionKey: 'website.access',
    },
    {
      label: 'Contenido',
      icon: 'FileText',
      layout: 'main',
      permissionKey: 'website.pages.read',
      children: [
        { label: 'Paginas',  path: '/pages', icon: 'FileText', permissionKey: 'website.pages.read' },
        { label: 'Blog',     path: '/blog',  icon: 'BookOpen', permissionKey: 'website.pages.read' },
      ],
    },
    {
      label: 'Diseno',
      icon: 'Palette',
      layout: 'main',
      permissionKey: 'website.theme.read',
      children: [
        { label: 'Tema',       path: '/theme',     icon: 'Palette',        permissionKey: 'website.theme.read' },
        { label: 'Plantillas', path: '/templates', icon: 'LayoutTemplate', permissionKey: 'website.pages.create' },
      ],
    },
    {
      label: 'Negocio',
      icon: 'CreditCard',
      layout: 'main',
      permissionKey: 'website.site.update',
      children: [
        { label: 'Formularios', path: '/forms',    icon: 'FormInput',  permissionKey: 'website.pages.read' },
        { label: 'Pagos',       path: '/payments', icon: 'CreditCard', permissionKey: 'website.site.update' },
      ],
    },
    {
      label: 'Configuracion',
      path: '/settings',
      icon: 'Settings',
      layout: 'main',
      permissionKey: 'website.site.update',
    },
  ],
});

export const runlyGrowthManifest = createModuleManifest({
  key: "runly.growth",
  name: "Growth",
  description: "Telemetria web, formularios y seguimiento de leads.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "TrendingUp",
  color: "#7C3AED",
  pwa: { shortName: "Growth", startPath: "/" },
  category: "comercial",
  summary: "Analitica de storefront y captura de oportunidades.",
  dependencies: [
    { key: "runly.core" },
    { key: "runly.website", optional: true },
    { key: "runly.contacts" },
  ],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: [
      "GrowthVisitor",
      "GrowthSession",
      "GrowthEvent",
      "GrowthLead",
      "GrowthLeadActivity",
      "GrowthDailyMetric",
      "GrowthProperty",
    ],
    ownedTables: [
      "growth_visitor",
      "growth_session",
      "growth_event",
      "growth_lead",
      "growth_lead_activity",
      "growth_daily_metric",
      "growth_property",
    ],
    sharedEntities: [
      "Company",
      "UserProfile",
      "Contact",
      "WebsiteSite",
      "WebsiteForm",
      "WebsiteFormSubmission",
    ],
  },
  navigation: [
    {
      label: "Crecimiento",
      path: "/",
      icon: "TrendingUp",
      layout: "main",
      permissionKey: "growth.analytics.read",
    },
    {
      label: "Leads",
      path: "/leads",
      icon: "UserRoundSearch",
      layout: "main",
      permissionKey: "growth.leads.read",
    },
    {
      label: "Sitios conectados",
      path: "/sites",
      icon: "Globe",
      layout: "main",
      permissionKey: "growth.access",
    },
    {
      label: "Formularios",
      path: "/forms",
      icon: "FileText",
      layout: "main",
      permissionKey: "growth.forms.read",
    },
  ],
  permissions: [
    { key: "growth.access", name: "Acceder a Growth" },
    { key: "growth.leads.read", name: "Ver leads" },
    { key: "growth.leads.create", name: "Crear leads" },
    { key: "growth.leads.update", name: "Editar leads" },
    { key: "growth.leads.delete", name: "Desactivar leads" },
    { key: "growth.leads.assign", name: "Asignar leads" },
    { key: "growth.leads.convert", name: "Convertir leads" },
    { key: "growth.analytics.read", name: "Ver analitica web" },
    { key: "growth.analytics.export", name: "Exportar analitica web" },
    { key: "growth.properties.manage", name: "Gestionar sitios conectados" },
    { key: "growth.forms.read", name: "Ver formularios" },
    { key: "growth.forms.create", name: "Crear formularios" },
    { key: "growth.forms.update", name: "Editar formularios" },
    { key: "growth.forms.delete", name: "Eliminar formularios" },
  ],
  acl: {
    module: "growth.access",
    actions: {
      "growth.leads.read": "growth.leads.read",
      "growth.leads.create": "growth.leads.create",
      "growth.leads.update": "growth.leads.update",
      "growth.leads.delete": "growth.leads.delete",
      "growth.leads.assign": "growth.leads.assign",
      "growth.leads.convert": "growth.leads.convert",
      "growth.analytics.read": "growth.analytics.read",
      "growth.analytics.export": "growth.analytics.export",
    },
    models: {
      GrowthLead: {
        read: "growth.leads.read",
        create: "growth.leads.create",
        update: "growth.leads.update",
        delete: "growth.leads.delete",
      },
      GrowthEvent: {
        read: "growth.analytics.read",
        create: "growth.analytics.read",
        update: "growth.analytics.read",
        delete: "growth.analytics.export",
      },
    },
  },
  blueprints: [],
});

export const runlyDocumentsManifest = createModuleManifest({
  key: "runly.documents",
  name: "Documentos",
  description: "Plantillas versionadas y documentos PDF generados.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Files",
  color: "#0F766E",
  pwa: { shortName: "Documentos", startPath: "/templates" },
  category: "productividad",
  summary: "Plantillas seguras y generacion de documentos PDF.",
  dependencies: [
    { key: "runly.core" },
    { key: "runly.files" },
    { key: "runly.company" },
  ],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: [
      "DocumentTemplate",
      "DocumentTemplateVersion",
      "GeneratedDocument",
    ],
    ownedTables: [
      "document_template",
      "document_template_version",
      "generated_document",
    ],
    sharedEntities: ["Company", "UserProfile", "FileAsset", "AuditLog"],
  },
  navigation: [
    {
      label: "Plantillas",
      path: "/templates",
      icon: "LayoutTemplate",
      layout: "main",
      permissionKey: "documents.templates.read",
    },
    {
      label: "Generados",
      path: "/generated",
      icon: "Files",
      layout: "main",
      permissionKey: "documents.generated.read",
    },
  ],
  permissions: [
    { key: "documents.access", name: "Acceder a Documentos" },
    { key: "documents.templates.read", name: "Ver plantillas" },
    { key: "documents.templates.create", name: "Crear plantillas" },
    { key: "documents.templates.update", name: "Editar plantillas" },
    { key: "documents.templates.delete", name: "Desactivar plantillas" },
    { key: "documents.templates.publish", name: "Publicar plantillas" },
    { key: "documents.generated.read", name: "Ver documentos generados" },
    { key: "documents.generated.create", name: "Generar documentos" },
    { key: "documents.generated.delete", name: "Desactivar documentos" },
  ],
  acl: {
    module: "documents.access",
    actions: {
      "documents.templates.read": "documents.templates.read",
      "documents.templates.create": "documents.templates.create",
      "documents.templates.update": "documents.templates.update",
      "documents.templates.delete": "documents.templates.delete",
      "documents.templates.publish": "documents.templates.publish",
      "documents.generated.read": "documents.generated.read",
      "documents.generated.create": "documents.generated.create",
      "documents.generated.delete": "documents.generated.delete",
    },
    models: {
      DocumentTemplate: {
        read: "documents.templates.read",
        create: "documents.templates.create",
        update: "documents.templates.update",
        delete: "documents.templates.delete",
      },
      DocumentTemplateVersion: {
        read: "documents.templates.read",
        create: "documents.templates.create",
        update: "documents.templates.update",
        delete: "documents.templates.delete",
      },
      GeneratedDocument: {
        read: "documents.generated.read",
        create: "documents.generated.create",
        update: "documents.generated.delete",
        delete: "documents.generated.delete",
      },
    },
  },
  blueprints: [],
});

export const featureModules = [];

export const activityMap = createModuleManifest({
  key: "runly.activity",
  name: "Actividad",
  description: "Bitácora legible de eventos y feed transversal de Runly ERP.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Activity",
  color: "#6366f1",
  pwa: { shortName: "Actividad", startPath: "/" },
  category: "plataforma",
  summary: "Feed de actividad de negocio en tiempo real",
  dependencies: [{ key: "runly.core" }, { key: "runly.identity" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["Activity"],
    sharedEntities: ["UserProfile", "Company"],
  },
  navigation: [
    {
      label: "Actividad",
      path: "/",
      icon: "Activity",
      layout: "main",
      permissionKey: "activity.read",
    },
  ],
  permissions: [
    { key: "activity.access", name: "Acceder al módulo de actividad" },
    { key: "activity.read", name: "Ver actividad" },
    { key: "activity.publish", name: "Publicar actividad" },
    { key: "activity.manage", name: "Administrar actividad" },
  ],
  exposes: {
    publishActivity: "function",
    logAndPublish: "function",
  },
  acl: {
    module: "activity.access",
    actions: {
      "activity.read": "activity.read",
      "activity.publish": "activity.publish",
      "activity.manage": "activity.manage",
      "activity.list": "activity.read",
      "activity.recent": "activity.read",
      "activity.entity": "activity.read",
    },
    models: {
      Activity: {
        read: "activity.read",
        create: "activity.publish",
        update: "activity.manage",
        delete: "activity.manage",
      },
    },
  },
  blueprints: [],
});

export const notificationsMap = createModuleManifest({
  key: "runly.notifications",
  name: "Notificaciones",
  description: "Alertas accionables para eventos importantes del sistema.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Bell",
  color: "#0ea5e9",
  pwa: { shortName: "Notificaciones", startPath: "/" },
  category: "plataforma",
  summary: "Inbox de notificaciones con prioridades y canales",
  dependencies: [{ key: "runly.core" }, { key: "runly.identity" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["Notification"],
    sharedEntities: ["UserProfile", "Company", "Activity"],
  },
  navigation: [
    {
      label: "Notificaciones",
      path: "/app/m/runly.notifications",
      icon: "Bell",
      layout: "main",
      permissionKey: "notifications.read",
    },
    {
      label: "Configuracion",
      path: "/app/m/runly.notifications/settings",
      icon: "Settings",
      layout: "main",
      permissionKey: "notifications.read",
    },
  ],
  permissions: [
    { key: "notifications.access", name: "Acceder a notificaciones" },
    { key: "notifications.read", name: "Ver notificaciones" },
    { key: "notifications.publish", name: "Publicar notificaciones" },
    { key: "notifications.manage", name: "Administrar notificaciones" },
  ],
  acl: {
    module: "notifications.access",
    actions: {
      "notifications.read": "notifications.read",
      "notifications.publish": "notifications.publish",
      "notifications.manage": "notifications.manage",
      "notifications.list": "notifications.read",
      "notifications.markRead": "notifications.read",
      "notifications.markAllRead": "notifications.read",
      "notifications.preferences.read": "notifications.read",
      "notifications.preferences.update": "notifications.read",
      "notifications.push.subscribe": "notifications.read",
      "notifications.push.unsubscribe": "notifications.read",
    },
    models: {
      Notification: {
        read: "notifications.read",
        create: "notifications.publish",
        update: "notifications.manage",
        delete: "notifications.manage",
      },
      NotificationDelivery: {
        read: "notifications.read",
        create: "notifications.publish",
        update: "notifications.manage",
        delete: "notifications.manage",
      },
      NotificationPreference: {
        read: "notifications.read",
        create: "notifications.read",
        update: "notifications.read",
        delete: "notifications.manage",
      },
      PushSubscription: {
        read: "notifications.read",
        create: "notifications.read",
        update: "notifications.read",
        delete: "notifications.read",
      },
    },
  },
  blueprints: [],
});

export const projectsMap = createModuleManifest({
  key: 'runly.projects',
  name: 'Proyectos',
  description: 'Gestion de proyectos y tareas con vistas Kanban, Lista y Timeline.',
  version: '1.0.0',
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: 'SquareKanban',
  color: '#09090b',
  pwa: { shortName: 'Proyectos', startPath: '/' },
  category: 'productividad',
  summary: 'Proyectos y tareas con Kanban, Lista y Timeline',
  dependencies: [
    { key: 'runly.identity' },
    { key: 'runly.company' },
    { key: 'runly.calendar', optional: true },
  ],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: 'purge-owned-tables',
    ownedEntities: ['Project', 'ProjectMember', 'TaskStatus', 'Task'],
    sharedEntities: ['UserProfile', 'Company'],
  },
  fullscreenPaths: ['/'],
  navigation: [
    {
      label: 'Proyectos',
      path: '/',
      icon: 'SquareKanban',
      layout: 'main',
      permissionKey: 'projects.access',
    },
  ],
  acl: {
    module: 'projects.access',
    actions: {
      'projects.project.read':   'projects.project.read',
      'projects.project.create': 'projects.project.create',
      'projects.task.read':      'projects.task.read',
    },
    models: {},
  },
  permissions: [
    { key: 'projects.access',          name: 'Acceder a Proyectos' },
    { key: 'projects.project.read',    name: 'Ver proyectos' },
    { key: 'projects.project.create',  name: 'Crear proyectos' },
    { key: 'projects.project.update',  name: 'Editar proyectos' },
    { key: 'projects.project.delete',  name: 'Archivar proyectos' },
    { key: 'projects.task.read',       name: 'Ver tareas' },
    { key: 'projects.task.create',     name: 'Crear tareas' },
    { key: 'projects.task.update',     name: 'Editar tareas' },
    { key: 'projects.task.delete',     name: 'Eliminar tareas' },
    { key: 'projects.member.manage',   name: 'Gestionar miembros' },
  ],
  exposes: {
    createTask: 'function',
  },
  blueprints: [],
});

export const chatMap = createModuleManifest({
  key: 'runly.chat',
  name: 'Chat',
  description: 'Mensajeria interna en tiempo real y chat de soporte para visitantes externos.',
  version: '0.2.0',
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: 'MessageSquare',
  color: '#8b5cf6',
  pwa: { shortName: 'Chat', startPath: '/chat/inbox' },
  category: 'comunicacion',
  summary: 'Chat interno y soporte en vivo',
  dependencies: [{ key: 'runly.core' }, { key: 'runly.identity' }],
  consumes: ['runly.notifications'],
  lifecycle: {
    installable: false,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: false,
  },
  navigation: [
    {
      label: 'Chat',
      path: '/chat/inbox',
      icon: 'MessageSquare',
      layout: 'main',
      permissionKey: 'chat.conversations.read',
    },
    {
      label: 'Bandeja externa',
      path: '/chat/external',
      icon: 'Inbox',
      layout: 'main',
      permissionKey: 'chat.support.manage',
    },
    {
      label: 'Plantillas',
      path: '/chat/templates',
      icon: 'LayoutTemplate',
      layout: 'main',
      permissionKey: 'chat.support.manage',
    },
  ],
  permissions: [
    { key: 'chat.access',               name: 'Acceder a Chat' },
    { key: 'chat.conversations.read',   name: 'Ver conversaciones' },
    { key: 'chat.conversations.create', name: 'Crear y enviar mensajes' },
    { key: 'chat.support.manage',       name: 'Gestionar soporte externo' },
    { key: 'chat.mirai.use',            name: 'Usar MirAI' },
    { key: 'chat.calls.record',         name: 'Grabar llamadas' },
    { key: 'chat.calls.transcript.request', name: 'Solicitar transcripción de llamadas' },
    { key: 'chat.calls.transcript.manage',  name: 'Administrar transcripciones de llamadas' },
    { key: 'chat.calls.transcript.analyze', name: 'Analizar transcripciones con MirAI' },
  ],
  acl: {
    module: 'chat.access',
    actions: {
      'chat.conversations.read':   'chat.conversations.read',
      'chat.conversations.create': 'chat.conversations.create',
      'chat.support.manage':       'chat.support.manage',
      'chat.mirai.use':            'chat.mirai.use',
      'chat.calls.record':         'chat.calls.record',
      'chat.calls.transcript.request': 'chat.calls.transcript.request',
      'chat.calls.transcript.manage':  'chat.calls.transcript.manage',
      'chat.calls.transcript.analyze': 'chat.calls.transcript.analyze',
    },
  },
  blueprints: [],
});
