// Generates api/automations.js (+ api/events.js for event triggers) from
// definition.automations. Spec docs/superpowers/specs/2026-10-04-builder-automations-design.md §4.3.
// The runtime is inlined so a published module needs nothing beyond
// moduleContext.services (record triggers) and the dispatcher's `services`
// (event triggers).
import { SERVICE_CONTRACTS } from '@runly/module-engine/contracts'

export function hasAutomations(config) {
  return Boolean(config.automations?.length)
}

export function hasEventAutomations(config) {
  return (config.automations ?? []).some((automation) => automation.trigger.type === 'event')
}

export function recordAutomationsFor(config, entityKey) {
  return (config.automations ?? []).filter((automation) => automation.trigger.type === 'record' && automation.trigger.entity === entityKey)
}

// Per automation, what the runtime needs to know about the contract.
function withRuntime(automation) {
  const args = SERVICE_CONTRACTS[automation.action.service]?.args ?? {}
  return {
    ...automation,
    runtime: {
      arrayArgs: Object.entries(args).filter(([, spec]) => spec.type.endsWith('[]')).map(([name]) => name),
      acceptsSource: Boolean(args.sourceEntityId),
    },
  }
}

export function generateAutomationsModule(config) {
  const list = config.automations.map(withRuntime)
  return `// Generated by the Module Builder from the module's automations. Edit them in
// the Builder (Automatizaciones), not here: this file is rewritten on publish.
export const AUTOMATIONS = ${JSON.stringify(list, null, 2)}

const isEmpty = (value) => value === undefined || value === null || value === '' || (Array.isArray(value) && value.length === 0)

export function matches(when, data, previous = null) {
  if (!when) return true
  const value = data?.[when.field]
  if (when.op === 'filled') return !isEmpty(value)
  if (when.op === 'changed') return Boolean(previous) && JSON.stringify(previous[when.field] ?? null) !== JSON.stringify(value ?? null)
  if (when.op === 'equals') return String(value ?? '') === String(when.value)
  return false
}

export function render(template, data) {
  return String(template).replace(/\\{\\{\\s*([a-zA-Z0-9_]+)\\s*\\}\\}/g, (_, key) => (data?.[key] === undefined || data?.[key] === null ? '' : String(data[key])))
}

function sourceValue(source, ctx) {
  if (source.from === 'value') return source.value
  if (source.from === 'field') return ctx.data?.[source.field]
  if (source.from === 'template') return render(source.template, ctx.data)
  if (source.from === 'recordId') return ctx.data?.id
  if (source.from === 'actor') return ctx.actorId
  return undefined
}

export function buildArgs(automation, ctx) {
  const args = {}
  for (const [name, source] of Object.entries(automation.action.args)) {
    let value = sourceValue(source, ctx)
    if (isEmpty(value)) continue
    if (automation.runtime.arrayArgs.includes(name) && !Array.isArray(value)) value = [value]
    args[name] = value
  }
  if (automation.runtime.acceptsSource && args.sourceEntityId === undefined && ctx.recordId) args.sourceEntityId = ctx.recordId
  if (ctx.idempotencyKey) args.idempotencyKey = ctx.idempotencyKey
  return args
}

// Runs after a record is created/updated. Never throws: a failed automation
// does not undo the save; the route returns the results and logs the error.
export async function runRecordAutomations({ c, moduleContext, entity, on, record, previous = null }) {
  const due = AUTOMATIONS.filter((a) => a.enabled && a.trigger.type === 'record' && a.trigger.entity === entity
    && (a.trigger.on === 'save' || a.trigger.on === on) && matches(a.trigger.when, record, previous))
  if (!due.length || !record) return []
  const services = moduleContext?.services?.forRequest?.(c)
  if (!services) return due.map((a) => ({ key: a.key, ok: false, error: 'Los servicios no están disponibles en esta instancia.' }))
  const actorId = c.get('userId') ?? null
  const results = []
  for (const automation of due) {
    try {
      await services.call(automation.action.service, buildArgs(automation, {
        data: record, recordId: record.id, actorId, idempotencyKey: on === 'create' ? automation.key + ':' + record.id + ':create' : null,
      }))
      results.push({ key: automation.key, ok: true })
    } catch (error) {
      console.error('[automatizaciones] ' + automation.key + ':', error?.message ?? error)
      results.push({ key: automation.key, ok: false, code: error?.code ?? null, error: String(error?.message ?? error) })
    }
  }
  return results
}

// api/events.js handlers: every matching automation, idempotent per event; a
// failure is rethrown after the loop so the dispatcher retries.
export function createEventHandlers() {
  const handlers = {}
  const events = [...new Set(AUTOMATIONS.filter((a) => a.trigger.type === 'event').map((a) => a.trigger.event))]
  for (const event of events) {
    handlers[event] = async ({ payload, eventId, services }) => {
      const due = AUTOMATIONS.filter((a) => a.enabled && a.trigger.type === 'event' && a.trigger.event === event && matches(a.trigger.when, payload))
      if (!due.length) return
      if (!services) throw new Error('Los servicios no están disponibles en esta instancia.')
      const failures = []
      for (const automation of due) {
        try {
          await services.call(automation.action.service, buildArgs(automation, { data: payload, actorId: null, idempotencyKey: automation.key + ':' + eventId }))
        } catch (error) {
          failures.push(automation.key + ': ' + (error?.message ?? error))
        }
      }
      if (failures.length) throw new Error(failures.join(' | '))
    }
  }
  return handlers
}
`
}

export function generateAutomationEvents() {
  return `// Generated by the Module Builder: system events that trigger automations.
import { createEventHandlers } from './automations.js'

export const handlers = createEventHandlers()
`
}
