import { moduleSlug, permKey } from './helpers.js'
import { resolveEntityLayout } from '../layout.js'

const FORM_TYPES = { textarea: 'textarea', number: 'number', decimal: 'decimal', boolean: 'boolean', select: 'select', multiselect: 'multiselect', date: 'date', datetime: 'datetime', email: 'email', phone: 'phone', relation: 'relation', file: 'file', json: 'json', markdown: 'markdown', color: 'color', richtext: 'richtext' }
const DETAIL_TYPES = { boolean: 'boolean', date: 'date', datetime: 'datetime', decimal: 'currency', number: 'number', color: 'color', markdown: 'markdown', richtext: 'richtext', file: 'file-asset' }

export function mapFormFieldType(type) {
  return FORM_TYPES[type] || 'text'
}

export function getDetailTypeHint(type) {
  return DETAIL_TYPES[type] || null
}

export function entityApiPath(config, entity) {
  return `/${moduleSlug(config.key)}/${entity.name}s`
}

// Module-scoped file endpoints generated by templates/file-routes.js.
export function entityFilePaths(config, entity) {
  const base = entityApiPath(config, entity)
  return {
    filesPath: `${base}/files`,
    signedUrlPath: `${base}/files/:id/signed-url`,
    listPath: `${base}/:id/files`,
    removePath: `${base}/:id/files/:docId`,
  }
}

export function entityFileType(config, entity) {
  return `${moduleSlug(config.key)}.${entity.name}`
}

export function hasFileSupport(entity) {
  if (entity.fields.some((field) => field.type === 'file')) return true
  return Boolean(entity.layout?.tabs?.some((tab) => tab.sections?.some((section) => section.type === 'attachments')))
}

export function fileFieldProps(config, entity, field) {
  const { filesPath, signedUrlPath } = entityFilePaths(config, entity)
  return { accept: field.accept ?? 'any', camera: Boolean(field.camera), maxSizeMB: field.maxSizeMB ?? 10, filesPath, signedUrlPath }
}

export function formFieldSpec(config, entity, field) {
  const spec = { field: field.name, label: field.label || field.name, type: mapFormFieldType(field.type) }
  if (field.required) spec.required = true
  if (field.type === 'select' && Array.isArray(field.options)) spec.options = field.options
  if (field.type === 'relation') {
    const target = field.relatedModel ? `${field.relatedModel.split('.').pop()}s` : `${field.name}s`
    spec.relation = { apiPath: `/${moduleSlug(config.key)}/${target}`, labelField: 'name', clearable: true }
  }
  if (field.type === 'file') Object.assign(spec, fileFieldProps(config, entity, field))
  return spec
}

export function detailFieldSpec(config, entity, field) {
  const spec = { field: field.name, label: field.label || field.name }
  const type = getDetailTypeHint(field.type)
  if (type) spec.type = type
  if (field.type === 'file') {
    spec.accept = field.accept ?? 'any'
    spec.signedUrlPath = entityFilePaths(config, entity).signedUrlPath
  }
  return spec
}

function attachmentsConfig(config, entity) {
  const slug = moduleSlug(config.key)
  const paths = entityFilePaths(config, entity)
  return {
    listPath: paths.listPath,
    upload: { endpoint: paths.filesPath, moduleKey: config.key, entityType: entityFileType(config, entity) },
    removePath: paths.removePath,
    signedUrl: { endpointTemplate: `${entityApiPath(config, entity)}/files/:fileId/signed-url` },
    fields: { fileAssetId: 'id', fileName: 'originalName' },
    limits: { maxFiles: 20, maxSizeMB: 10, allowMultiple: true },
    permissions: {
      read: permKey(slug, entity.name, 'read'),
      create: permKey(slug, entity.name, 'update'),
      remove: permKey(slug, entity.name, 'update'),
      fileUpload: permKey(slug, entity.name, 'update'),
      fileRead: permKey(slug, entity.name, 'read'),
    },
  }
}

function layoutSections(config, entity, layout, fieldSpec, { attachmentsColumn } = {}) {
  const fieldsByName = new Map(entity.fields.map((field) => [field.name, field]))
  const multiTab = layout.tabs.length > 1
  return layout.tabs.flatMap((tab) => tab.sections.map((section) => {
    const base = { id: section.key, label: section.label, ...(multiTab ? { tab: tab.key } : {}) }
    if (section.type === 'attachments') {
      return { ...base, type: 'attachments', placement: section.placement ?? 'embedded', ...(attachmentsColumn ? { column: attachmentsColumn } : {}), attachments: attachmentsConfig(config, entity) }
    }
    return {
      ...base,
      columns: section.columns ?? 2,
      fields: (section.fields ?? []).map((name) => fieldSpec(config, entity, fieldsByName.get(name))),
    }
  }))
}

function tabsList(layout) {
  return layout.tabs.length > 1 ? layout.tabs.map((tab) => ({ key: tab.key, label: tab.label })) : undefined
}

function emitView(key, kind, schema) {
  const body = JSON.stringify({ key, kind, version: '0.1.0', schema }, null, 2)
  return `import { defineView } from '@runly/module-engine'\n\nexport default defineView(${body})\n`
}

// Converts a ModuleDefinition entity to the template shape used here (the
// same mapping compiler.js#toTemplateConfig applies), so the Builder can
// build preview schemas without compiling the whole module.
export function toLayoutTemplateEntity(moduleKey, entity) {
  return {
    ...entity,
    name: entity.key,
    labelPlural: entity.pluralLabel,
    fields: (entity.fields ?? []).map((field) => ({
      ...field,
      name: field.key,
      options: field.options?.map((option) => (typeof option === 'object' ? option.value : option)),
      relatedModel: field.targetModel ?? (field.targetEntity ? `${moduleKey.split('.').pop()}.${field.targetEntity}` : undefined),
    })),
  }
}

export function buildLayoutFormSchema(config, entity) {
  const layout = resolveEntityLayout(entity)
  if (!layout) return null
  return {
    entity: entity.name,
    component: 'RunlyForm',
    apiPath: entityApiPath(config, entity),
    ...(layout.mode && layout.mode !== 'auto' ? { formMode: layout.mode } : {}),
    ...(tabsList(layout) ? { tabs: tabsList(layout) } : {}),
    sections: layoutSections(config, entity, layout, formFieldSpec),
    submitLabel: `Guardar ${entity.label.toLowerCase()}`,
    cancelLabel: 'Cancelar',
  }
}

export function generateLayoutFormView(config, entity) {
  const schema = buildLayoutFormSchema(config, entity)
  return schema ? emitView(`${moduleSlug(config.key)}.${entity.name}.form`, 'FORM', schema) : null
}

export function buildLayoutDetailSchema(config, entity) {
  const layout = resolveEntityLayout(entity)
  if (!layout) return null
  const slug = moduleSlug(config.key)
  const detail = layout.detail ?? {}
  const hero = detail.hero?.titleField ? {
    titleField: detail.hero.titleField,
    ...(detail.hero.subtitleFields?.length ? { subtitleFields: detail.hero.subtitleFields } : {}),
    ...(detail.hero.statusField ? { statusField: detail.hero.statusField } : {}),
    ...(detail.hero.imageField ? { imageField: detail.hero.imageField, signedUrlPath: entityFilePaths(config, entity).signedUrlPath } : {}),
  } : null
  return {
    entity: entity.name,
    component: 'RunlyDetail',
    apiPath: entityApiPath(config, entity),
    ...(hero ? { hero } : {}),
    ...(detail.kpis?.length ? { kpis: detail.kpis.map((kpi) => ({ field: kpi.field, label: kpi.label })) } : {}),
    ...(detail.twoColumn ? { layout: 'two-column' } : {}),
    ...(tabsList(layout) ? { tabs: tabsList(layout) } : {}),
    sections: layoutSections(config, entity, layout, detailFieldSpec, { attachmentsColumn: detail.twoColumn ? 'aside' : undefined }),
    actions: [
      { label: 'Editar', permission: permKey(slug, entity.name, 'update') },
      { label: 'Desactivar', permission: permKey(slug, entity.name, 'delete') },
    ],
  }
}

export function generateLayoutDetailView(config, entity) {
  const schema = buildLayoutDetailSchema(config, entity)
  return schema ? emitView(`${moduleSlug(config.key)}.${entity.name}.detail`, 'DETAIL', schema) : null
}
