import { test, describe, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, rmSync, readdirSync, existsSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { resolve, join } from 'node:path'
import { execFileSync } from 'node:child_process'
import { writeModule, applyDefaults } from '../writer.js'

const DEMO_CONFIG = applyDefaults({
  key: 'custom.e2edemo',
  name: 'E2E Demo',
  version: '0.1.0',
  description: 'Generated by e2e test',
  icon: 'Box',
  color: '#6366f1',
  pwa: {
    shortName: 'E2E Demo',
    startPath: '/e2edemo-items',
  },
  entities: [
    {
      name: 'item',
      label: 'Item',
      labelPlural: 'Items',
      softDelete: true,
      companyScoped: true,
      fields: [
        { name: 'title', type: 'text', label: 'Titulo', required: true },
        { name: 'status', type: 'select', label: 'Estado', options: ['activo', 'inactivo'] },
        { name: 'notes', type: 'textarea', label: 'Notas' },
      ],
    },
  ],
})

// Override REPO_ROOT to write into a temp dir
// We monkey-patch by providing a custom repoRoot to writeModule directly
let tempRoot
let result

describe('e2e scaffold smoke test', () => {
  before(() => {
    tempRoot = mkdtempSync(join(tmpdir(), 'atlas-scaffold-e2e-'))
    result = writeModule(DEMO_CONFIG, tempRoot)
  })

  after(() => {
    rmSync(tempRoot, { recursive: true, force: true })
  })

  test('writes the expected number of files', () => {
    // 1 manifest + 1 service-helpers + 1 api/index + 1 validators/index
    // + per entity: 1 model + 4 views + 1 routes + 1 service + 1 validators = 8
    // total = source definition + 4 shared + 8 entity files = 13
    assert.equal(result.written.length, 13)
  })

  test('module.manifest.js exists', () => {
    const path = resolve(result.outDir, 'module.manifest.js')
    assert.ok(existsSync(path), 'module.manifest.js should exist')
  })

  test('api/index.js exists', () => {
    assert.ok(existsSync(resolve(result.outDir, 'api/index.js')))
  })

  test('api/service-helpers.js exists', () => {
    assert.ok(existsSync(resolve(result.outDir, 'api/service-helpers.js')))
  })

  test('validators/index.js exists', () => {
    assert.ok(existsSync(resolve(result.outDir, 'validators/index.js')))
  })

  test('models/item.model.js exists', () => {
    assert.ok(existsSync(resolve(result.outDir, 'models/item.model.js')))
  })

  test('all view files exist', () => {
    for (const kind of ['table', 'form', 'detail', 'page']) {
      const path = resolve(result.outDir, `views/item.${kind}.js`)
      assert.ok(existsSync(path), `views/item.${kind}.js should exist`)
    }
  })

  test('api/item-routes.js exists', () => {
    assert.ok(existsSync(resolve(result.outDir, 'api/item-routes.js')))
  })

  test('api/item-service.js exists', () => {
    assert.ok(existsSync(resolve(result.outDir, 'api/item-service.js')))
  })

  test('validators/item.validators.js exists', () => {
    assert.ok(existsSync(resolve(result.outDir, 'validators/item.validators.js')))
  })

  test('all generated files pass node --check (syntax valid)', () => {
    for (const relPath of result.written) {
      if (relPath.endsWith('.json')) continue
      const absPath = resolve(result.outDir, relPath)
      try {
        execFileSync(process.execPath, ['--check', absPath], { stdio: 'pipe' })
      } catch (err) {
        assert.fail(`Syntax error in ${relPath}:\n${err.stderr?.toString() ?? err.message}`)
      }
    }
  })
})

describe('e2e scaffold smoke test (crud-custom preset)', () => {
  let customRoot
  let customResult

  before(() => {
    customRoot = mkdtempSync(join(tmpdir(), 'atlas-scaffold-custom-'))
    customResult = writeModule(
      applyDefaults({
        ...DEMO_CONFIG,
        key: 'custom.e2ecustom',
        preset: 'crud-custom',
      }),
      customRoot
    )
  })

  after(() => {
    rmSync(customRoot, { recursive: true, force: true })
  })

  test('writes custom view and component files for crud-custom preset', () => {
    assert.ok(customResult.written.includes('views/dashboard.custom.js'))
    assert.ok(customResult.written.includes('components/index.js'))
    assert.ok(customResult.written.includes('components/ModuleDashboard.jsx'))
  })

  test('module manifest references the generated custom dashboard view', () => {
    const manifest = readdirSync(resolve(customResult.outDir)).includes('module.manifest.js')
    assert.ok(manifest, 'module.manifest.js should exist for crud-custom preset')
    const content = readFileSync(resolve(customResult.outDir, 'module.manifest.js'), 'utf8')
    assert.match(content, /\.\/views\/dashboard\.custom\.js/)
  })
})
